### ISSUE TITLE
Windows build instructions

### ISSUE THREAD

**Issue by gkralik** [gkralik/php7-sapnwrfc#8]
Some instructions for building on Windows would be a nice enhancement.But as I personally don't use Windows, I can't provide them. 

@ThaDafinser could you provide instructions on doing that? Even if we can add builds to the releases (and I'm a great fan of doing so as it lowers the barrier of using the extension) some people might want to compile themselves.

**Comment by ThaDafinser** [comment]
I can provide some instructions, already saw some somewhere in your repo.
In general with a proper `config.w32` you just need to follow https://wiki.php.net/internals/windows/stepbystepbuild
and have the SAPNWRFC in the right location

Yeah builds are important to add. about 1 year ago i didnt know how todo that myself...

The question is how we can "sync" that in the future...that's why i wanted to add it to `pecl` ...but there we need the NWRFC as well :cry:

**Comment by gkralik** [comment]
I'm closing this (PR #10 remains open until I'm done with the docs update).
